### ISSUE TITLE
reference to yamllint.yml in meta_skeleton is no longer available

### ISSUE THREAD

**Issue by Jakuje** [oasis-roles/meta_standards#28]
The readme references yamllint.yml configuration, which is is no longer available:
 
> All YAML files need to pass standard yamllint syntax with the modifications listed in tests/yamllint.yml in the meta_skeleton role. These modifications are minimal: document starter characters (the initial --- string at the top of a file) should not be used, and it is not necessary to start every comment with a space. Most comments should start with a space, but no space is allowed when a comment is documenting an optional variable with its default value. 

Instead, the official galaxy importer lint should probably be used: https://github.com/ansible/galaxy/blob/devel/galaxy/importer/linters/yamllint.yaml

**Comment by greg-hellings** [comment]
We still maintain the tests, they're now imported as a submodule from [here](https://github.com/oasis-roles/meta_test). So the docs are still present, you just have to follow through two levels. The README from the skeleton tells you where to get the tests submodule from.

**Comment by Jakuje** [comment]
Thank you for the pointer. That is really not clear from the reading of the paragraph and from my reading of the repository. Would it make sense to update the readme either to direct link or at least point to the correct repository?

**Comment by greg-hellings** [comment]
It most definitely would! If it was confusing to you, then let's figure out a way to craft it so you and anyone else approaching the question newly can understand it more easily.

If you have a suggested edit, feel free to submit it. It might be better for you to address it, since your nose isn't down in the details?
